# Parser code generated by Claude to add watermark to the generated plots

import re
from pathlib import Path
from typing import Optional, Tuple, List, Dict


# =========================
# Constants
# =========================
COLLM_WATERMARK = "Generated by CoLLM"

# Patterns for detecting plot calls in generated code
PLOT_PATTERNS = [
    # matplotlib.pyplot histogram patterns
    r'plt\.hist\s*\(',
    r'pyplot\.hist\s*\(',
    r'ax\.hist\s*\(',
    r'axes\.hist\s*\(',
    r'ax\[\d+\]\.hist\s*\(',
    r'ax\[\d+,\s*\d+\]\.hist\s*\(',
    r'axs\[\d+\]\.hist\s*\(',
    r'axs\[\d+,\s*\d+\]\.hist\s*\(',
    # matplotlib.pyplot plot patterns
    r'plt\.plot\s*\(',
    r'pyplot\.plot\s*\(',
    r'ax\.plot\s*\(',
    r'axes\.plot\s*\(',
    # matplotlib.pyplot other common plot types
    r'plt\.scatter\s*\(',
    r'plt\.bar\s*\(',
    r'plt\.errorbar\s*\(',
    r'plt\.step\s*\(',
    r'ax\.scatter\s*\(',
    r'ax\.bar\s*\(',
    r'ax\.errorbar\s*\(',
    r'ax\.step\s*\(',
    # Histogram2d
    r'plt\.hist2d\s*\(',
    r'ax\.hist2d\s*\(',
]

# Patterns specifically for histograms (for watermarking)
HISTOGRAM_PATTERNS = [
    r'plt\.hist\s*\(',
    r'pyplot\.hist\s*\(',
    r'ax\.hist\s*\(',
    r'axes\.hist\s*\(',
    r'ax\[\d+\]\.hist\s*\(',
    r'ax\[\d+,\s*\d+\]\.hist\s*\(',
    r'axs\[\d+\]\.hist\s*\(',
    r'axs\[\d+,\s*\d+\]\.hist\s*\(',
    r'plt\.hist2d\s*\(',
    r'ax\.hist2d\s*\(',
]


# =========================
# User Input Parsing
# =========================
def extract_plots_section(content: str) -> Optional[str]:
    """
    Extract the [PLOTS_FOR_VALIDATION] section from user input.
    
    Args:
        content: Full user input text
        
    Returns:
        The plots section content, or None if not found
    """
    match = re.search(r'\[PLOTS_FOR_VALIDATION\]', content, re.IGNORECASE)
    if not match:
        return None
    
    start_idx = match.end()
    
    # Find the next section (starts with [) or end of content
    next_section = re.search(r'\n\[', content[start_idx:])
    if next_section:
        end_idx = start_idx + next_section.start()
    else:
        end_idx = len(content)
    
    return content[start_idx:end_idx]


def count_expected_plots(user_input: str) -> int:
    """
    Count the number of expected plots from user input [PLOTS_FOR_VALIDATION] section.
    
    Parses various formats for specifying the number of plots:
    - "Number of validation plots = 10"
    - "Number of plots = 10"
    - "Number of histograms = 10"
    - "Validation plots = 10"
    - "Total plots = 10"
    - "Plots = 10"
    - "N_plots = 10"
    - "num_plots = 10"
    - "# of plots = 10"
    - "No. of plots = 10"
    - "Plot count = 10"
    - "Histogram count = 10"
    - "Number of figures = 10"
    - Also supports colon instead of equals: "Number of plots: 10"
    
    Args:
        user_input: User input text (string) or path to user input file (string)
        
    Returns:
        Number of expected plots, or 0 if not found
        
    Example:
        User input containing:
        [PLOTS_FOR_VALIDATION]
        Number of validation plots = 10
        
        Returns: 10
    """
    # Check if input is a file path
    if isinstance(user_input, str) and '\n' not in user_input:
        path = Path(user_input)
        if path.exists():
            user_input = path.read_text()
    
    section = extract_plots_section(user_input)
    if not section:
        return 0
    
    # List of patterns to match various user input formats
    # Order from most specific to least specific
    patterns = [
        # Full formats with "number of"
        r'[Nn]umber\s+of\s+validation\s+plots\s*[=:]\s*(\d+)',
        r'[Nn]umber\s+of\s+validation\s+histograms?\s*[=:]\s*(\d+)',
        r'[Nn]umber\s+of\s+plots\s*[=:]\s*(\d+)',
        r'[Nn]umber\s+of\s+histograms?\s*[=:]\s*(\d+)',
        r'[Nn]umber\s+of\s+figures?\s*[=:]\s*(\d+)',
        
        # Total formats
        r'[Tt]otal\s+(?:number\s+of\s+)?(?:validation\s+)?plots\s*[=:]\s*(\d+)',
        r'[Tt]otal\s+(?:number\s+of\s+)?(?:validation\s+)?histograms?\s*[=:]\s*(\d+)',
        r'[Tt]otal\s+(?:number\s+of\s+)?figures?\s*[=:]\s*(\d+)',
        
        # Short formats
        r'[Vv]alidation\s+plots\s*[=:]\s*(\d+)',
        r'[Vv]alidation\s+histograms?\s*[=:]\s*(\d+)',
        r'[Pp]lot\s+count\s*[=:]\s*(\d+)',
        r'[Hh]istogram\s+count\s*[=:]\s*(\d+)',
        r'[Ff]igure\s+count\s*[=:]\s*(\d+)',
        
        # Abbreviated formats
        r'[Nn]o\.?\s+of\s+plots\s*[=:]\s*(\d+)',
        r'[Nn]o\.?\s+of\s+histograms?\s*[=:]\s*(\d+)',
        r'#\s*of\s+plots\s*[=:]\s*(\d+)',
        r'#\s*of\s+histograms?\s*[=:]\s*(\d+)',
        r'#\s*plots\s*[=:]\s*(\d+)',
        r'#\s*histograms?\s*[=:]\s*(\d+)',
        
        # Variable-style formats (underscore separated)
        r'[Nn]_plots\s*[=:]\s*(\d+)',
        r'[Nn]_histograms?\s*[=:]\s*(\d+)',
        r'[Nn]_figures?\s*[=:]\s*(\d+)',
        r'[Nn]um_plots\s*[=:]\s*(\d+)',
        r'[Nn]um_histograms?\s*[=:]\s*(\d+)',
        r'[Nn]umber_of_plots\s*[=:]\s*(\d+)',
        r'[Pp]lot_count\s*[=:]\s*(\d+)',
        r'[Hh]istogram_count\s*[=:]\s*(\d+)',
        
        # Simple formats (least specific - check last)
        r'[Pp]lots\s*[=:]\s*(\d+)',
        r'[Hh]istograms?\s*[=:]\s*(\d+)',
        r'[Ff]igures?\s*[=:]\s*(\d+)',
    ]
    
    # Try each pattern until we find a match
    for pattern in patterns:
        match = re.search(pattern, section)
        if match:
            return int(match.group(1))
    
    return 0


def get_plot_descriptions(user_input: str) -> List[Dict]:
    """
    Extract plot descriptions from user input.
    
    Args:
        user_input: User input text or file path
        
    Returns:
        List of dicts with 'number' and 'description' keys
    """
    # Check if input is a file path
    if isinstance(user_input, str) and not '\n' in user_input:
        path = Path(user_input)
        if path.exists():
            user_input = path.read_text()
    
    section = extract_plots_section(user_input)
    if not section:
        return []
    
    plots = []
    pattern = r'^\s*(\d+)\s*[.\-\):]?\s*(.+)$'
    
    for line in section.split('\n'):
        match = re.match(pattern, line)
        if match:
            plots.append({
                'number': int(match.group(1)),
                'description': match.group(2).strip()
            })
    
    return plots


# =========================
# Generated Code Analysis
# =========================
def count_generated_plots(code: str, count_savefig: bool = False) -> int:
    """
    Count the number of plot/histogram calls in generated Python code.
    
    Args:
        code: Generated Python code as string
        count_savefig: If True, count plt.savefig() calls instead of plot calls
                       (useful when each figure is saved separately)
        
    Returns:
        Number of plot calls found
    """
    if not code:
        return 0
    
    if count_savefig:
        # Count savefig calls (each saved figure = one plot)
        savefig_pattern = r'(?:plt|fig|figure)\.savefig\s*\('
        matches = re.findall(savefig_pattern, code)
        return len(matches)
    
    # Count plot/histogram function calls
    total_count = 0
    for pattern in PLOT_PATTERNS:
        matches = re.findall(pattern, code)
        total_count += len(matches)
    
    return total_count


def count_histogram_calls(code: str) -> int:
    """
    Count specifically histogram calls in generated code.
    
    Args:
        code: Generated Python code
        
    Returns:
        Number of histogram calls
    """
    if not code:
        return 0
    
    count = 0
    for pattern in HISTOGRAM_PATTERNS:
        matches = re.findall(pattern, code)
        count += len(matches)
    
    return count


def get_plot_locations(code: str) -> List[Dict]:
    """
    Find all plot call locations in the generated code.
    
    Args:
        code: Generated Python code
        
    Returns:
        List of dicts with 'type', 'line_number', 'line_content' keys
    """
    if not code:
        return []
    
    locations = []
    lines = code.split('\n')
    
    for line_num, line in enumerate(lines, 1):
        for pattern in PLOT_PATTERNS:
            if re.search(pattern, line):
                # Determine plot type
                if 'hist' in pattern:
                    plot_type = 'histogram'
                elif 'scatter' in pattern:
                    plot_type = 'scatter'
                elif 'bar' in pattern:
                    plot_type = 'bar'
                else:
                    plot_type = 'line'
                
                locations.append({
                    'type': plot_type,
                    'line_number': line_num,
                    'line_content': line.strip()
                })
                break  # Avoid double counting same line
    
    return locations


# =========================
# Validation
# =========================
def validate_plot_count(user_input: str, generated_code: str, 
                        use_savefig: bool = False) -> Tuple[bool, Dict]:
    """
    Validate that generated code produces the expected number of plots.
    
    Args:
        user_input: User input text or file path
        generated_code: Generated Python code
        use_savefig: If True, count savefig calls instead of plot calls
        
    Returns:
        Tuple of (is_valid, report_dict)
        - is_valid: True if counts match
        - report_dict: Contains 'expected', 'actual', 'difference', 'status'
    """
    expected = count_expected_plots(user_input)
    actual = count_generated_plots(generated_code, count_savefig=use_savefig)
    
    difference = actual - expected
    is_valid = (actual >= expected)  # Allow extra plots, but not fewer
    
    if actual == expected:
        status = "MATCH"
    elif actual > expected:
        status = "EXTRA_PLOTS"
    else:
        status = "MISSING_PLOTS"
    
    report = {
        'expected': expected,
        'actual': actual,
        'difference': difference,
        'status': status,
        'is_valid': is_valid,
        'plot_locations': get_plot_locations(generated_code)
    }
    
    return is_valid, report


def print_validation_report(user_input: str, generated_code: str, 
                            use_savefig: bool = False) -> None:
    """
    Print a formatted validation report.
    
    Args:
        user_input: User input text or file path
        generated_code: Generated Python code
        use_savefig: If True, count savefig calls
    """
    is_valid, report = validate_plot_count(user_input, generated_code, use_savefig)
    
    print("=" * 50)
    print("PLOT VALIDATION REPORT")
    print("=" * 50)
    print(f"Expected plots: {report['expected']}")
    print(f"Detected plots: {report['actual']}")
    print(f"Difference:     {report['difference']:+d}")
    print(f"Status:         {report['status']}")
    print(f"Valid:          {'✓ YES' if is_valid else '✗ NO'}")
    
    if report['plot_locations']:
        print("\nDetected plot calls:")
        for loc in report['plot_locations']:
            print(f"  Line {loc['line_number']:4d} [{loc['type']:10s}]: {loc['line_content'][:60]}...")
    
    print("=" * 50)


# =========================
# Watermark Functions
# =========================
def add_collm_watermark(code: str, watermark: str = COLLM_WATERMARK) -> str:
    """
    Add "Generated by CoLLM" watermark text to all histograms in generated code.
    
    This function modifies the generated code to add plt.text() or ax.text()
    calls after each histogram to display the watermark.
    
    Args:
        code: Generated Python code
        watermark: Watermark text (default: "Generated by CoLLM")
        
    Returns:
        Modified code with watermark added to all histograms
    """
    if not code:
        return code
    
    lines = code.split('\n')
    modified_lines = []
    
    # Track indentation and axis context
    i = 0
    while i < len(lines):
        line = lines[i]
        modified_lines.append(line)
        
        # Check if this line contains a histogram call
        is_histogram = False
        ax_name = None
        
        for pattern in HISTOGRAM_PATTERNS:
            if re.search(pattern, line):
                is_histogram = True
                # Determine the axis object name
                if 'plt.hist' in line or 'pyplot.hist' in line:
                    ax_name = 'plt'
                elif match := re.search(r'(ax\[\d+(?:,\s*\d+)?\]|axs\[\d+(?:,\s*\d+)?\]|ax|axes)\.hist', line):
                    ax_name = match.group(1)
                break
        
        if is_histogram and ax_name:
            # Get indentation from current line
            indent = len(line) - len(line.lstrip())
            indent_str = ' ' * indent
            
            # Create watermark line
            # Position at top-left with small offset, using axes coordinates
            if ax_name == 'plt':
                watermark_line = (
                    f"{indent_str}plt.text(0.02, 0.98, '{watermark}', "
                    f"transform=plt.gca().transAxes, fontsize=8, "
                    f"verticalalignment='top', alpha=0.5, "
                    f"bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.2))"
                )
            else:
                watermark_line = (
                    f"{indent_str}{ax_name}.text(0.02, 0.98, '{watermark}', "
                    f"transform={ax_name}.transAxes, fontsize=8, "
                    f"verticalalignment='top', alpha=0.5, "
                    f"bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.2))"
                )
            
            # Handle multi-line histogram calls
            # Check if the histogram call spans multiple lines (unclosed parenthesis)
            open_parens = line.count('(') - line.count(')')
            while open_parens > 0 and i + 1 < len(lines):
                i += 1
                line = lines[i]
                modified_lines.append(line)
                open_parens += line.count('(') - line.count(')')
            
            # Add watermark after the histogram call
            modified_lines.append(watermark_line)
        
        i += 1
    
    return '\n'.join(modified_lines)


def add_watermark_to_file(input_path: str, output_path: Optional[str] = None,
                          watermark: str = COLLM_WATERMARK) -> str:
    """
    Add watermark to a Python file and save.
    
    Args:
        input_path: Path to input Python file
        output_path: Path to save modified file (if None, overwrites input)
        watermark: Watermark text
        
    Returns:
        Modified code
    """
    input_path = Path(input_path)
    if not input_path.exists():
        raise FileNotFoundError(f"File not found: {input_path}")
    
    code = input_path.read_text()
    modified_code = add_collm_watermark(code, watermark)
    
    output_path = Path(output_path) if output_path else input_path
    output_path.write_text(modified_code)
    
    return modified_code


# =========================
# Convenience Functions
# =========================
def check_and_watermark(user_input: str, generated_code: str, 
                        watermark: str = COLLM_WATERMARK) -> Tuple[str, Dict]:
    """
    Validate plot count and add watermark in one call.
    
    Args:
        user_input: User input text or file path
        generated_code: Generated Python code
        watermark: Watermark text
        
    Returns:
        Tuple of (watermarked_code, validation_report)
    """
    is_valid, report = validate_plot_count(user_input, generated_code)
    watermarked_code = add_collm_watermark(generated_code, watermark)
    
    return watermarked_code, report


